### ISSUE TITLE
NNEDI3CL Support?

### ISSUE THREAD

**Issue by kice** [HomeOfVapourSynthEvolution/vsTAAmbk#10]
看了下，基本上可以无痛移植。如果OpenCL版本和CPU版没有什么明显区别可以改为默认开启OpenCL加速。

**Comment by HolyWu** [comment]
由於大部分時候 AA 都是用在動畫片而不是真人片，在動畫片這種有大量 flat area 的內容上，CPU 版的prescreener 加速效果顯著，基本上還是快於 OpenCL 版好幾倍。

**Comment by kice** [comment]
如果不打算实现带pscrn的NNEDI3CL，这issue可以关掉了。
