### ISSUE TITLE
sharpens by default

### ISSUE THREAD

**Issue by kgrabs** [HomeOfVapourSynthEvolution/vsTAAmbk#11]
Because of the if/else sharpening part of the code not accounting for sharp==0 it still sharpens with LSFmod(strength=0)

Confirmed with benchmark, 140 fps with sharp=0 and 250 fps with sharp=-2

Oh another issue, I wanted to use the fastest aatype for the benchmark but I think PointSangNom is broken:
```
Failed to evaluate the script:
Python exception: __init__() takes from 2 to 3 positional arguments but 4 were given

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 1830, in vapoursynth.vpy_evaluateScript (src\cython\vapoursynth.c:36860)
File "C:/Users/Zastin/Documents/taa test.vpy", line 6, in 
taa.TAAmbk(srcY, aatype=6, sharp=0).set_output()
File "C:\Users\Zastin\AppData\Local\Programs\Python\Python36\lib\site-packages\vsTAAmbk.py", line 632, in TAAmbk
y = aa_kernel[aatype](y, strength, down8, opencl=opencl, opencl_device=opencl_device, **args).out()
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by kewenyu** [comment]
Fixed in v0.7.4

**Comment by kgrabs** [comment]
Nice. I just thought to check: for the fmtc.resample lines you can get another small speed boost setting flt=False. Only since it uses float precision internally and rounds back to integer. It also falls back to float if needed so it's safe to always have it enabled

**Comment by kewenyu** [comment]
But the default values of the flt is false already since fmtconv r5. So we needn't to specify it explicitly. By the way, most resizing in vsTAAmbk is using internal resizer now. Only if the user use Vapoursynth older than R33 will it use fmtc instead.
