### ISSUE TITLE
 Deprecation Warning

### ISSUE THREAD

**Issue by nobananasforyou** [HomeOfVapourSynthEvolution/vsTAAmbk#19]
I get the following warning when I call taa.TAAmbk(src)

site-packages\vsTAAmbk.py:25: DeprecationWarning: register_format() is deprecated. Use "query_video_format" instead.
vs.GRAY10 = self.core.register_format(vs.GRAY, vs.INTEGER, 10, 0, 0).id

**Comment by kewenyu** [comment]
fixed.
