### ISSUE TITLE
replace or remove eedi2cuda (amusement ver.) ?

### ISSUE THREAD

**Issue by hooke007** [HomeOfVapourSynthEvolution/vsTAAmbk#20]
The repo was removed.
ref https://github.com/AmusementClub/tools/issues/1
Original ver. https://github.com/ruihe774/VapourSynth-EEDI2CUDA

**Comment by kewenyu** [comment]
vsTAAmbk should work well with original version of eeid2cuda. I'll update README.md to point the link to the original one. Thanks for report.
